"use client";

import Link from "next/link";
import type { CSSProperties, RefObject } from "react";
import type { GalleryTile } from "@/content/gallery";
import { useKitchen } from "@/lib/store";

/**
 * One picture on the infinite wall.
 *
 * A `next/link` rather than a div with a handler, because it IS a link: the
 * middle-click, the copied address and the keyboard all come free. Every tile
 * points at its own picture inside the study -- `/work/<slug>#media-<name>` --
 * so a visitor who liked one screen lands on the paragraph that explains it
 * rather than at the top of a long article.
 *
 * A plain <img> with a two-size srcset: 480px for an ordinary screen and 960px
 * for a dense one, generated by scripts/gallery-tiles.mjs. A print is drawn at
 * about 400 CSS px, so `sizes` says so and the browser picks the file that
 * covers it -- a 1x screen never downloads the retina set.
 */
export function InfiniteTile({
  tile,
  style,
  elRef,
  dragged,
}: {
  tile: GalleryTile;
  style: CSSProperties;
  elRef: (el: HTMLAnchorElement | null) => void;
  /** Set by a touch drag, so a drag never navigates. */
  dragged: RefObject<boolean>;
}) {
  return (
    <Link
      ref={elRef}
      href={tile.href}
      className="infinite-tile"
      /*
       * No viewport prefetch. Every link on the wall is "in view" from the
       * moment the layer mounts -- it is transparent, not unlaid-out -- so the
       * default warmed the RSC payload of every case study on a visit to the
       * kitchen, work nobody asked for. It also turned the can popover's own
       * hover prefetch into a cache hit that never hit the network, and
       * `case-study.spec.ts` caught it.
       */
      prefetch={false}
      style={style}
      draggable={false}
      onClick={(e) => {
        if (dragged.current) {
          e.preventDefault();
          return;
        }
        // Told on the way out, not on the way in: this page unmounts the moment
        // the route changes, so anything that has to leave has to be told by
        // the click that causes it.
        useKitchen.getState().setLeavingKitchen(true);
      }}
    >
      {/* eslint-disable-next-line @next/next/no-img-element -- see above. */}
      <img
        src={tile.src}
        srcSet={`${tile.src} 480w, ${tile.src2x} 960w`}
        sizes="420px"
        alt={tile.alt}
        width={tile.width}
        height={tile.height}
        loading="lazy"
        decoding="async"
        draggable={false}
      />
    </Link>
  );
}
