// GENERATED by scripts/normalize-assets.mjs -- do not edit.
// The image-trail cursor's pool. Dimensions are measured off the files,
// so the trail never has to guess an aspect ratio.
export type TrailImage = { src: string; width: number; height: number };

export const TRAIL: TrailImage[] = [
  {"src":"/assets/trail/trail-01.webp","width":440,"height":587},
  {"src":"/assets/trail/trail-02.webp","width":440,"height":587},
  {"src":"/assets/trail/trail-03.webp","width":440,"height":550},
  {"src":"/assets/trail/trail-04.webp","width":440,"height":587},
  {"src":"/assets/trail/trail-05.webp","width":440,"height":587},
  {"src":"/assets/trail/trail-06.webp","width":440,"height":780},
  {"src":"/assets/trail/trail-07.webp","width":440,"height":587},
  {"src":"/assets/trail/trail-08.webp","width":440,"height":536},
];
