// GENERATED by scripts/normalize-assets.mjs -- do not edit.
// Dimensions are measured off the files themselves, which is what keeps
// aspect ratios honest and the page free of layout shift.
import type { Loop, Media } from "./types";

export const MEDIA = {
  "metamask/01-intro": {"src":"/assets/case-studies/metamask/01-intro.webp","alt":"MetaMask Card onboarding, before the redesign","width":1071,"height":585},
  "metamask/02-funding-drop-off": {"src":"/assets/case-studies/metamask/02-funding-drop-off.webp","alt":"The unguided funding step that dropped users into a swap interface","width":549,"height":599},
  "metamask/03-spending-limit": {"src":"/assets/case-studies/metamask/03-spending-limit.webp","alt":"The delegation screen and its $2,192,020.00 default spending cap","width":549,"height":599},
  "metamask/04-stepper": {"src":"/assets/case-studies/metamask/04-stepper.webp","alt":"The four-step onboarding stepper","width":755,"height":300},
  "metamask/05-dashboard-states": {"src":"/assets/case-studies/metamask/05-dashboard-states.webp","alt":"Dashboard states for users who did not finish onboarding","width":1424,"height":600},
  "bonadocs/01-hero": {"src":"/assets/case-studies/bonadocs/01-hero.webp","alt":"The Bonadocs widget embedded in a documentation page","width":2240,"height":1260},
  "bonadocs/03-user-interview": {"src":"/assets/case-studies/bonadocs/03-user-interview.webp","alt":"A Jobs-to-be-Done interview with a Web3 developer","width":3840,"height":2160},
  "bonadocs/04-journey-map": {"src":"/assets/case-studies/bonadocs/04-journey-map.webp","alt":"The user journey map built from the interview insights","width":2660,"height":1214},
  "bonadocs/05-affinity-diagram": {"src":"/assets/case-studies/bonadocs/05-affinity-diagram.webp","alt":"Affinity diagram clustering usability feedback","width":1488,"height":638},
  "bonadocs/06-sketches": {"src":"/assets/case-studies/bonadocs/06-sketches.webp","alt":"Early sketches of the widget","width":906,"height":362},
  "bonadocs/07-wireframes": {"src":"/assets/case-studies/bonadocs/07-wireframes.webp","alt":"Low-fidelity wireframes for querying a contract method","width":1396,"height":730},
  "bonadocs/08-moodboard": {"src":"/assets/case-studies/bonadocs/08-moodboard.webp","alt":"Moodboard for the widget interface","width":920,"height":632},
  "bonadocs/09-first-hifi": {"src":"/assets/case-studies/bonadocs/09-first-hifi.webp","alt":"First high-fidelity explorations","width":1516,"height":1102},
  "bonadocs/11-round-two-feedback": {"src":"/assets/case-studies/bonadocs/11-round-two-feedback.webp","alt":"Participant feedback from the second usability round","width":3410,"height":1644},
  "bonadocs/16-consensys-fellowship": {"src":"/assets/case-studies/bonadocs/16-consensys-fellowship.webp","alt":"Selected for the maiden Consensys fellowship programme","width":1920,"height":1080},
  "passportmonie/01-app-icon": {"src":"/assets/case-studies/passportmonie/01-app-icon.webp","alt":"The PassportMonie app icon over a textured gradient","width":3840,"height":2160},
  "passportmonie/02-logotype": {"src":"/assets/case-studies/passportmonie/02-logotype.webp","alt":"The PassportMonie logotype","width":3840,"height":2160},
  "passportmonie/03-color": {"src":"/assets/case-studies/passportmonie/03-color.webp","alt":"Brand colors: Deep Current, Bold Velocity, Neon Pulse, Clear Horizon, Friendly Glow, Ice White","width":3840,"height":2160},
  "passportmonie/04-typography": {"src":"/assets/case-studies/passportmonie/04-typography.webp","alt":"DM Sans as the primary typeface, and why","width":3840,"height":2160},
  "passportmonie/05-gradients": {"src":"/assets/case-studies/passportmonie/05-gradients.webp","alt":"Spectral, textured brand gradients","width":3840,"height":2160},
  "passportmonie/06-art-direction": {"src":"/assets/case-studies/passportmonie/06-art-direction.webp","alt":"Art direction: Lagos iconography, botanical texture, vintage gadgetry","width":3840,"height":2160},
  "passportmonie/07-tone-of-voice": {"src":"/assets/case-studies/passportmonie/07-tone-of-voice.webp","alt":"Tone of voice: fast and direct, versatile, personable and warm, empowering","width":3840,"height":2160},
  "passportmonie/08-merch": {"src":"/assets/case-studies/passportmonie/08-merch.webp","alt":"Brand applied to merchandise","width":3840,"height":2160},
  "passportmonie/09-onboarding": {"src":"/assets/case-studies/passportmonie/09-onboarding.webp","alt":"Onboarding screens carrying the illustrated system","width":3840,"height":2160},
  "passportmonie/10-product-screens": {"src":"/assets/case-studies/passportmonie/10-product-screens.webp","alt":"Product screens with wallet card backgrounds and setup banners","width":3840,"height":2160},
  "passportmonie/11-in-product": {"src":"/assets/case-studies/passportmonie/11-in-product.webp","alt":"AI illustration in the live product: wallet card, setup banners, and the Carter Bridge on clouds","width":1724,"height":1211},
  "passportmonie/12-icon-set": {"src":"/assets/case-studies/passportmonie/12-icon-set.webp","alt":"The icon set, themed to the same material palette","width":1724,"height":1089},
  "dean/01-logo-mockups": {"src":"/assets/case-studies/dean/01-logo-mockups.webp","alt":"DEAN logo mockups across physical applications","width":2880,"height":1620},
  "fagbemi-studios/01-brand-reel": {"src":"/assets/case-studies/fagbemi-studios/01-brand-reel.webp","alt":"Fagbemi Studios identity across renders, photography and the quote card","width":3840,"height":2160},
  "fagbemi-studios/02-exhibition": {"src":"/assets/case-studies/fagbemi-studios/02-exhibition.webp","alt":"Light and Shadow: an exhibition poster in garnet and gold, the monogram set over an oval portrait","width":2160,"height":2700},
  "fagbemi-studios/03-work-in-progress": {"src":"/assets/case-studies/fagbemi-studios/03-work-in-progress.webp","alt":"The artist at the easel, a portrait in progress under available light","width":2160,"height":2700},
} as const satisfies Record<string, Media>;

export const LOOPS = {
  "bonadocs/02-widget-in-docs": {"src":"/assets/case-studies/bonadocs/02-widget-in-docs.gif","still":"/assets/case-studies/bonadocs/02-widget-in-docs-still.webp","alt":"The widget running inside the Lido documentation","width":1119,"height":630},
  "bonadocs/10-userflow-first": {"src":"/assets/case-studies/bonadocs/10-userflow-first.gif","still":"/assets/case-studies/bonadocs/10-userflow-first-still.webp","alt":"The first user-flow exploration, recorded","width":800,"height":800},
  "bonadocs/12-userflow-revised": {"src":"/assets/case-studies/bonadocs/12-userflow-revised.gif","still":"/assets/case-studies/bonadocs/12-userflow-revised-still.webp","alt":"The revised user flow, recorded","width":800,"height":800},
  "bonadocs/13-mainnet-query": {"src":"/assets/case-studies/bonadocs/13-mainnet-query.gif","still":"/assets/case-studies/bonadocs/13-mainnet-query-still.webp","alt":"Querying the mainnet from inside the docs","width":900,"height":900},
  "bonadocs/14-array-properties": {"src":"/assets/case-studies/bonadocs/14-array-properties.gif","still":"/assets/case-studies/bonadocs/14-array-properties-still.webp","alt":"Adding array properties that carry tuples of parameters","width":900,"height":900},
  "bonadocs/15-parameter-tabs": {"src":"/assets/case-studies/bonadocs/15-parameter-tabs.gif","still":"/assets/case-studies/bonadocs/15-parameter-tabs-still.webp","alt":"Switching between method and transaction parameters","width":900,"height":900},
} as const satisfies Record<string, Loop>;

export type MediaKey = keyof typeof MEDIA;
export type LoopKey = keyof typeof LOOPS;
