// GENERATED by scripts/fetch-vimeo-posters.mjs -- do not edit.
export const VIMEO = {
  "metamask/compatible-tokens": {"id":"1180546615","poster":"/assets/case-studies/metamask/poster-compatible-tokens.webp","title":"Compatible-Tokens","width":1200,"height":720},
  "metamask/connect-wallet": {"id":"1180546642","poster":"/assets/case-studies/metamask/poster-connect-wallet.webp","title":"Connect-Wallet","width":1200,"height":675},
  "metamask/showreel": {"id":"1180546666","poster":"/assets/case-studies/metamask/poster-showreel.webp","title":"MetaMask Card Showreel","width":1200,"height":675},
  "metamask/funding": {"id":"1180546718","poster":"/assets/case-studies/metamask/poster-funding.webp","title":"Funding","width":1200,"height":675},
  "metamask/select-assets": {"id":"1181009581","poster":"/assets/case-studies/metamask/poster-select-assets.webp","title":"Select-Assets-to-Spend (1)","width":1200,"height":2000},
  "dean/showcase": {"id":"1190987210","poster":"/assets/case-studies/dean/poster-showcase.webp","title":"Dean Showcase","width":1200,"height":675},
} as const;

export type VimeoKey = keyof typeof VIMEO;
